Phase04
Star-Academy/Summer1400-SE-Team13 pull request #4
Opened 2021-08-01 08:12 UTC by Melikad

2021-08-03 13:25 UTC, nedataghizadeh79 commented on phase04/Student.cs
> +        {
میتوانستید برای زیبایی بیشتر از توابع آماده برای یافتن معدل استفاده نمایید.

2021-08-03 14:11 UTC, hoseinaghaei requested changes

2021-08-03 14:11 UTC, hoseinaghaei commented on .vscode/launch.json
> +    "version": "0.2.0",
این باید بره تو گیت ایگنور

2021-08-03 14:11 UTC, hoseinaghaei commented on .vscode/tasks.json
> +    "version": "2.0.0",
اینم باید بره تو گیت ایگنور

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/DataManager.cs
> +    class DataManager
اسم بهتر

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/DataManager.cs
> +        public List<T> DeserializeObject<T>(string json)
اسم ورودی بهتر

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/FileReader.cs
> +        }
بار ۱۰۰۰ام
کار با 
ّIO
میکنین همیشه اکسپشن هارو پیش بینی کنین

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/Grade.cs
> +        public Grade(int studentNumber, string lesson, double score)
چون کلاس قراره توسط 
json deserializer
ساخته بشه نیاز نیست کانستراکتور بذارین

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/Program.cs
> +            organizer.Run(fileReader, dataManager);
بهتره تابع ران خروجی داشته باشه

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/ScoresOrganizer.cs
> +            string studentsJsonInput = fileReader.ReadData("Students.json");
ادرس رو هارد کد ندین

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/ScoresOrganizer.cs
> +        public void GetData(FileReader fileReader, DataManager dataManager)
اینجا برید برای دوتا کلاس ورودی اینترفیس بذارین
چون برای تست باید ماک بشن

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/ScoresOrganizer.cs
> +            return StudentsList.Where(Student => Student.StudentNumber == studentNumber).First();
تو خود تابع 
First
میتونید شرط بذارین

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/ScoresOrganizer.cs
> +        public void PrintOutput()
کار 
IO
رو به یک اینترفیس جداگانه بدین
به کلاس 
ScoresOrganizer
ربطی نداره پرینت کردن

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/ScoresOrganizer.cs
> +            StudentsList.Sort((a, b) => b.GPA.CompareTo(a.GPA));
از تابع
OrderBy
لینک استفاده کنید

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/ScoresOrganizer.cs
> +            for(int i = 0; i < 3; i++)
با کمک لینک بعد از سورت کردن با استفاده از تابع 
Take
میتونید هرتعدادی که خواستین بگیرین
و نیاز نیست دیه فور با i بزنین

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/ScoresOrganizer.cs
> +        public void AddGrades()
اسم بد

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/ScoresOrganizer.cs
> +                Student student = FindStudent(grade.StudentNumber);
برید راجج
Join & GroupJoin
تو لینک بخونین
و سعی کنین با کمک اون بزنید کدتون رو

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/ScoresOrganizer.cs
> +        public void SetGPAs()
اسم درست

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/Student.cs
> +    class Student
کلا ساختار کلاس بده
وقتی یک شی رو دیسریالاز میکنین باید همون فیلدهای تو جیسون رو فقط براش بذارین
الان خوانایی کد خیلی بده

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/bin/Debug/net5.0/phase04.deps.json
> +  "runtimeTarget": {
گیت ایگنور

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/bin/Debug/net5.0/phase04.runtimeconfig.dev.json
> +  "runtimeOptions": {
گیت ایگنور
کلی فایل 
dll
دیگم پوش کردین
برین درستش کنین

2021-08-03 14:11 UTC, hoseinaghaei commented on phase04/obj/Debug/net5.0/phase04.AssemblyInfo.cs
> +// <auto-generated>
بجز کلاس های 
.cs و 
.csproj
و دوتا جیسون دیتا همه چی باید بره تو گیت ایگنور

2021-08-07 17:03 UTC, Parsa2820 reviewed
خوب بود. خسته نباشید

2021-08-07 17:03 UTC, Parsa2820 commented on phase04/Grade.cs
> +﻿namespace ConsoleApp1
<p dir="rtl">
واسه 
namespace 
اسم درست بذارید
</p>

2021-08-07 17:03 UTC, Parsa2820 commented on phase04/IO.cs
> +        public string ToString(Student student, double GPA)
اسم تابع رو یه چیز دیگه بذارید

2021-08-07 17:03 UTC, Parsa2820 commented on phase04/IO.cs
> +            var firstThreeStudents = studentsList.Take(3);
خوبه که عدد 3 رو به عنوان ورودی بگیرید و هاردکد نباشه

2021-08-07 17:03 UTC, Parsa2820 commented on phase04/JsonConverter.cs
> +            return JsonSerializer.Deserialize<List<T>>(jsonFileContent);
<p dir="rtl">
واسه همین یه خط کلاس نوشتید؟ اسم تابع گمراه کنندس. تایپ T ه ولی به 
</p>
List &ltT&gt
<p dir="rtl">
 دیسریالایز میکنه
</p>

2021-08-07 17:03 UTC, Parsa2820 commented on phase04/ScoresOrganizer.cs
> +            foreach (var student in _studentsList)
میتونید با لینک هم بنویسید
var studentAverageMap = _studentsList.ToDictionary(s => s, 
        studentsGrades
            .Where(grade => grade.StudentNumber == student.StudentNumber)
            .Select(grade => grade.Score)
            .Average());

2021-08-07 17:03 UTC, Parsa2820 commented on phase04/ScoresOrganizer.cs
> +            return SetStudentAverage().OrderByDescending(x => x.Value).ToDictionary(x => x.Key, x => x.Value);
ToDictionary 
واسه چی زدید؟

2021-08-08 05:27 UTC, rahaahmadi commented on phase04/ScoresOrganizer.cs
> +            return SetStudentAverage().OrderByDescending(x => x.Value).ToDictionary(x => x.Key, x => x.Value);
خروجیش
IOrderedEnumerable 
بود میخواستیم دیکشنری باشه

2021-08-08 09:31 UTC, hoseinaghaei requested changes

2021-08-08 09:31 UTC, hoseinaghaei commented on Phase04/Phase04/IO.cs
> +        private string OutputString(Student student, double GPA)
اسم تابع خوب نیست

2021-08-08 09:31 UTC, hoseinaghaei commented on Phase04/Phase04/IO.cs
> +        private string OutputString(Student student, double GPA)
اینم بگم، حالا اینجا شی
student
کلا ۳ تا فیلد دارع و شما دوتاش نیاز داشتین تو این تابع
اما اگر یک جایی فیلد شی بیشتر باشع و شما هم به یکی دوتا فیلدش نیاز داشته باشین باید فیلدهاش پاس بدین نه خودشو

2021-08-08 09:31 UTC, hoseinaghaei commented on Phase04/Phase04/IO.cs
> +        public void PrintOutput(Dictionary<Student, double> studentsList, int numberOfStudentToPrint)
اینکه کل پراسس رو انجام بدیم روی همه داده ها و تهش موقع پرینت تعداد مشخص کنیم کار خوبی نیست
شما میتونی موقع پراسس تعداد رو تاثیر بدی

2021-08-08 09:31 UTC, hoseinaghaei commented on Phase04/Phase04/Program.cs
> +            var scoresList = jsonConverter.GetDeserializedObjects<Grade>(io.GetInput("JsonData/Scores.json"));
ادرس هارو کانست بالای تابع یا کلاس تعریف کنید

2021-08-08 09:31 UTC, hoseinaghaei commented on Phase04/Phase04/JsonConverter.cs
> +            return JsonSerializer.Deserialize<List<T>>(jsonFileContent);
بهتره تو کار با لیست های بزرگ و این حرفا بجای لیست از 
IEnumrable
استفاده کنید
چون شاید اصلا نیاز نشه که روی همش کوئری بزنیم

2021-08-08 09:31 UTC, hoseinaghaei commented on Phase04/Phase04/ScoresOrganizer.cs
> +            return _studentsList.Join(_scoresList, std => std.StudentNumber, grade => grade.StudentNumber, (std, grade) => grade).ToList();
چون یک کار تقریبا پیچیده داره انجام میشه بهتره اول بریزین تو ی متغییر که با اسمش کسی که داره کد رو میخونه بفهمه برای چی زدینش و بعد اونو ریترن کنین

2021-08-08 09:31 UTC, hoseinaghaei commented on Phase04/Phase04/ScoresOrganizer.cs
> +        private Dictionary<Student, double> SetStudentAverage()
تابع ست خروجی نداره
اسم بهتر برای تابع

2021-08-08 09:31 UTC, hoseinaghaei commented on Phase04/Phase04/ScoresOrganizer.cs
> +                 }).ToDictionary(x => x.Student, x => x.Average);
اینجا اول یک شی
Anonymous 
ساختین بعد تبدیل کردین هردو فیلدش رو به دیکشنری
خب از اول دیکشنری بسازین
یا کلا یک کلاس بسازین که تو خودش 
student & average
داره و اونو ریترن کنین

2021-08-08 12:17 UTC, merged